service: mailchimp-cleaned-webhook # NOTE: update this with your service name
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: go1.x
  region: eu-west-1
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:*'
      Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  contactform:
    handler: bin/cleaned-email-notify
    events:
      - http:
          path: /
          method: post
  ping:
    handler: bin/ping
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-dotenv-plugin
